### ISSUE TITLE
Font gets too small when graph gets big

### ISSUE THREAD

**Issue by olligobber** [arthurbthiele/word-journey#1]
![2021-10-20-174822_1919x969_scrot](https://user-images.githubusercontent.com/11549963/138042084-44a8797d-9687-4cd2-a98e-99eaec00c5cf.png)

**Comment by arthurbthiele** [comment]
Resolved by Commit 35b7750. Double clicking anywhere on graph now fits graph to screen, and zooming is fully enabled.
